- name: Push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add data/  # Forzamos a que agregue la carpeta data
          git commit -m "Actualización de datos: $(date +'%Y-%m-%d')" || echo "No hay cambios para subir"
          git push
